### ISSUE TITLE
Alignment computation

### ISSUE THREAD

**Issue by tristanpwdennis** [giffordlabcvr/gluetools#1]
[Mus.Zeta.txt](https://github.com/giffordlabcvr/gluetools/files/117460/Mus.Zeta.txt)

Tried to compute an alignment of ERV sequences using the blast aligner module:

GLUE> compute alignment Mus.Zeta blastAligner 
13:29:26.349 ComputeAlignmentCommand FINEST: Searching for members to align
13:29:26.369 ComputeAlignmentCommand FINEST: Found 36 members to align
Exception in thread "main" java.lang.NullPointerException
    at uk.ac.gla.cvr.gluetools.core.command.project.ComputeAlignmentCommand.applyMemberAlignedSegments(ComputeAlignmentCommand.java:196)
    at uk.ac.gla.cvr.gluetools.core.command.project.ComputeAlignmentCommand.getBatchResult(ComputeAlignmentCommand.java:134)
    at uk.ac.gla.cvr.gluetools.core.command.project.ComputeAlignmentCommand.getAllAlignResults(ComputeAlignmentCommand.java:112)
    at uk.ac.gla.cvr.gluetools.core.command.project.ComputeAlignmentCommand.execute(ComputeAlignmentCommand.java:96)
    at uk.ac.gla.cvr.gluetools.core.command.project.ComputeAlignmentCommand.execute(ComputeAlignmentCommand.java:50)
    at uk.ac.gla.cvr.gluetools.core.console.Console.executeTokenStrings(Console.java:176)
    at uk.ac.gla.cvr.gluetools.core.console.Console.executeTokenStrings(Console.java:127)
    at uk.ac.gla.cvr.gluetools.core.console.Console.handleLine(Console.java:117)
    at uk.ac.gla.cvr.gluetools.core.console.Console.handleInteractiveLine(Console.java:91)
    at uk.ac.gla.cvr.gluetools.core.console.Console.interactiveSession(Console.java:377)
    at uk.ac.gla.cvr.gluetools.core.console.Console.main(Console.java:296)

GLUE then exits to shell

**Comment by tristanpwdennis** [comment]
Similar problem in v0.1.44

11:25:41.764 CommandCompleter WARNING: java.lang.NoSuchMethodException: uk.ac.gla.cvr.gluetools.core.command.project.CreateAlignmentCommand$Completer.<init>()
11:25:41.940 CommandCompleter WARNING: Failed to instantiate command completer class uk.ac.gla.cvr.gluetools.core.command.project.CreateAlignmentCommand.Completer

**Comment by joshsinger** [comment]
I believe the compute alignment issue has now been fixed.
