### ISSUE TITLE
Import source

### ISSUE THREAD

**Issue by tristanpwdennis** [giffordlabcvr/gluetools#2]
GLUE> create source MGRV2
Exception in thread "main" org.apache.cayenne.CayenneRuntimeException: [v.3.1 Sep 20 2014 14:06:21] Commit Exception
    at org.apache.cayenne.access.DataContext.flushToParent(DataContext.java:845)
    at org.apache.cayenne.access.DataContext.commitChanges(DataContext.java:756)
    at uk.ac.gla.cvr.gluetools.core.command.CommandContext.commit(CommandContext.java:137)
    at uk.ac.gla.cvr.gluetools.core.command.project.CreateSourceCommand.execute(CreateSourceCommand.java:46)
    at uk.ac.gla.cvr.gluetools.core.command.project.CreateSourceCommand.execute(CreateSourceCommand.java:19)
    at uk.ac.gla.cvr.gluetools.core.console.Console.executeTokenStrings(Console.java:176)
    at uk.ac.gla.cvr.gluetools.core.console.Console.executeTokenStrings(Console.java:127)
    at uk.ac.gla.cvr.gluetools.core.console.Console.handleLine(Console.java:117)
    at uk.ac.gla.cvr.gluetools.core.console.Console.handleInteractiveLine(Console.java:91)
    at uk.ac.gla.cvr.gluetools.core.console.Console.interactiveSession(Console.java:378)
    at uk.ac.gla.cvr.gluetools.core.console.Console.main(Console.java:296)
Caused by: java.sql.BatchUpdateException: Duplicate entry 'MGRV2' for key 'PRIMARY'
    at com.mysql.jdbc.PreparedStatement.executeBatchSerially(PreparedStatement.java:1819)
    at com.mysql.jdbc.PreparedStatement.executeBatch(PreparedStatement.java:1281)
    at org.apache.cayenne.access.jdbc.BatchAction.runAsBatch(BatchAction.java:143)
    at org.apache.cayenne.access.jdbc.BatchAction.performAction(BatchAction.java:83)
    at org.apache.cayenne.access.DataNodeQueryAction.runQuery(DataNodeQueryAction.java:87)
    at org.apache.cayenne.access.DataNode.performQueries(DataNode.java:280)
    at org.apache.cayenne.access.DataDomainFlushAction.runQueries(DataDomainFlushAction.java:233)
    at org.apache.cayenne.access.DataDomainFlushAction.flush(DataDomainFlushAction.java:154)
    at org.apache.cayenne.access.DataDomain.onSyncFlush(DataDomain.java:853)
    at org.apache.cayenne.access.DataDomain$2.transform(DataDomain.java:817)
    at org.apache.cayenne.access.DataDomain.runInTransaction(DataDomain.java:877)
    at org.apache.cayenne.access.DataDomain.onSyncNoFilters(DataDomain.java:814)
    at org.apache.cayenne.access.DataDomain$DataDomainSyncFilterChain.onSync(DataDomain.java:1031)
    at org.apache.cayenne.access.DataDomain.onSync(DataDomain.java:785)
    at org.apache.cayenne.access.DataContext.flushToParent(DataContext.java:817)
    ... 10 more
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry 'MGRV2' for key 'PRIMARY'
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
    at com.mysql.jdbc.Util.handleNewInstance(Util.java:389)
    at com.mysql.jdbc.Util.getInstance(Util.java:372)
    at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:973)
    at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3835)
    at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3771)
    at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2435)
    at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2582)
    at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2535)
    at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1911)
    at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2145)
    at com.mysql.jdbc.PreparedStatement.executeBatchSerially(PreparedStatement.java:1777)

**Comment by joshsinger** [comment]
So the issue here was (a) GLUE throws an error if it's a non-sequence file, rather than skipping the file with a warning and (b) after the error, the GLUE engine is left in an inconsistent state such that the next time you run "import source" it fails with the error you posted.

This will be fixed in the next release. Until then, the workaround is to make sure any non-sequence files are not in the directory. If you get an error because of a non-sequence file, restart GLUE and redo the import and it should work.
