### ISSUE TITLE
Exception on "quit" after project build

### ISSUE THREAD

**Issue by daveuu** [giffordlabcvr/gluetools#7]
I'm not sure if this is really a problem but after `run file hcvProject.glue` had completed with `OK`, I typed in `quit` and got this:
```
GLUE> quit
OK
Exception in thread "main" org.apache.cayenne.CayenneRuntimeException: [v.3.1.1 Apr 29 2016 12:50:34] Error invoking event method shutdown
        at org.apache.cayenne.di.spi.ScopeEventBinding.onScopeEvent(ScopeEventBinding.java:67)
        at org.apache.cayenne.di.spi.DefaultScope.postScopeEvent(DefaultScope.java:145)
        at org.apache.cayenne.di.spi.DefaultScope.shutdown(DefaultScope.java:75)
        at org.apache.cayenne.di.spi.DefaultInjector.shutdown(DefaultInjector.java:138)
        at org.apache.cayenne.configuration.CayenneRuntime.shutdown(CayenneRuntime.java:166)
        at uk.ac.gla.cvr.gluetools.core.GluetoolsEngine.dispose(GluetoolsEngine.java:195)
        at uk.ac.gla.cvr.gluetools.core.GluetoolsEngine.shutdown(GluetoolsEngine.java:189)
        at uk.ac.gla.cvr.gluetools.core.console.Console.shutdown(Console.java:571)
        at uk.ac.gla.cvr.gluetools.core.console.Console.main(Console.java:385)
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.cayenne.di.spi.ScopeEventBinding.onScopeEvent(ScopeEventBinding.java:61)
        ... 8 more
Caused by: org.apache.cayenne.CayenneRuntimeException: [v.3.1.1 Apr 29 2016 12:50:34] Error while shutting down
        at org.apache.cayenne.conn.PoolManager.beforeScopeEnd(PoolManager.java:236)
        at org.apache.cayenne.configuration.server.DelegatingDataSourceFactory.shutdown(DelegatingDataSourceFactory.java:76)
        ... 12 more
```

**Comment by robjgiff** [comment]
Hi David,

I think Josh might be on leave today - if he hasn’t responded that’s probably why.

I sometimes get these error messages on GLUE exit, especially if I have had the shell open a long time. I don’t think it indicates a problem.

Cheers,

Rob

**Comment by joshsinger** [comment]
I've also seen this occasionally / intermittently. It doesn't seem to have any negative consequences so I haven't investigated it yet.
